 export APP_NAME="miumiu"
 export POSTGRESQL_ADDON_HOST="127.0.0.1"
 export POSTGRESQL_ADDON_PORT="5432"
 export POSTGRESQL_ADDON_DB="authdb"
 export POSTGRESQL_ADDON_USER="miumiu"
 export POSTGRESQL_ADDON_PASSWORD="miumiu"
 export LEVEL="DEBUG"
 